version: '3.2'
services:
  api:
    image: starter-api:latest
    container_name: starter-api
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/starter
      - DATABASE_PASSWORD=password
      - DATABASE_USER=starter

  postgres:
    container_name: starter-postgres
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=starter
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=starter
